name: Deploy to Server (Production)

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  SSH_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ vars.SERVERUSER }}
  APP_DIR: u1/StandardERPServer/

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.T }}

      - name: Validate server connection
        run: ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "echo 'Successfully connected to server'"

      - name: Pull latest changes from main
        run: |
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            cd $APP_DIR
            git fetch origin
            git reset --hard origin/main
          "

      - name: Stop existing server using script
        run: |
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            cd $APP_DIR
            chmod +x stop-hansa.sh
            ./stop-hansa.sh
          "

      - name: Start server using script
        run: |
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            cd $APP_DIR
            chmod +x start-hansa.sh
            nohup ./start-hansa.sh > hansa.log 2>&1 &
          "

      - name: Check server log
        run: |
          sleep 60
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "tail -n 20 $APP_DIR/hansa.log"

      - name: Verify server status
        run: |
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            ps aux | grep '[S]tandardERPServer64' | grep -- '--port 1201' || (echo 'Server not running' && exit 1)
          "

      - name: Rollback on failure
        if: failure()
        run: |
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            cd $APP_DIR
            tail -n 20 $APP_DIR/hal.log
            echo 'Rolling back to previous version...'
            git reset --hard HEAD@{1}
            ./stop-hansa.sh
            nohup ./start-hansa.sh > hal.log 2>&1 &
            echo 'Rollback to previous commit completed'
          "
