name: Test Deployment on PR

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  SSH_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER:  ${{ vars.SERVERUSER }}
  APP_DIR: u1/StandardERPServer/

jobs:
  test-deploy:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.T }}

      - name: Validate server connection
        run: ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "echo 'Successfully connected to server'"

      - name: Force update to test branch
        run: |
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            set -e
            cd $APP_DIR
            git fetch origin
            git reset --hard origin/${{ github.head_ref }}
          "

      - name: Stop existing server using script
        run: |
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            cd $APP_DIR
            chmod +x stop-hansa.sh
            ./stop-hansa.sh
          "

      - name: Start server using script
        run: |
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            cd $APP_DIR
            chmod +x start-hansa.sh
            nohup ./start-hansa.sh > hansa.log 2>&1 &
            echo 'Start script executed'
          "

      - name: Wait and check server log
        run: |
          sleep 60
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "tail -n 20 $APP_DIR/hansa.log"

      - name: Verify server status
        run: |
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            ps aux | grep '[S]tandardERPServer64' | grep -- '--port 1201' || (echo 'Server not running' && exit 1)
          "

      - name: Deploy production code from main (on success)
        if: success()
        run: |
          echo "Test deployment succeeded. Deploying main branch to production..."
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            cd $APP_DIR
            git fetch origin
            git reset --hard origin/main
            ./stop-hansa.sh
            sleep 2
            nohup ./start-hansa.sh > hansa.log 2>&1 &
            echo 'Main branch deployed and server restarted'
          "

      - name: Rollback to production code (on failure)
        if: failure()
        run: |
          echo "Test deployment failed. Rolling back to main branch..."
          ssh -p $SSH_PORT $SERVER_USER@$SERVER_IP "
            cd $APP_DIR
            cat hal.log
            git fetch origin
            git reset --hard origin/main
            ./stop-hansa.sh
            sleep 2
            nohup ./start-hansa.sh > hansa.log 2>&1 &
            echo 'Rollback to main branch completed'
          "
